### ISSUE TITLE
Add infinite placeholders based on player, not rank

### ISSUE THREAD

**Issue by Folas1337** [Efnilite/Walk-in-the-Park#103]
**Describe the bug**
Using `/papi parse me %witp_rank%` only yields the output %witp_rank% and not the actual rank.

**To Reproduce**
1. Install WITP/IP
2. Install PAPI
3. Check `/papi parse me %witp_rank%` after having played one round

**Screenshots**
*Hopefully not required.*

**Errors**
Couldn't find anything in the logs that would hint to an error

**Versions**
- Plugin version: 5.1.0
- PAPI version: 2.11.3
- Spigot/Paper version: 1.19.4 build 550

**Comment by Efnilite** [comment]
`%witp_rank%` only works when you're playing the parkour.

**Comment by Folas1337** [comment]
Oh but why's that? I thought it'd be nice to use it for some leaderboards or is there another placeholder I should use for that?

**Comment by Folas1337** [comment]
Also I am absolutely positive it wasn't always this way, I've been using it before but at some point it must've broken :(

**Comment by Efnilite** [comment]
> Oh but why's that? I thought it'd be nice to use it for some leaderboards or is there another placeholder I should use for that?

It used to be the case that your highscore was stored with your other data like settings. Settings were only loaded when you joined the parkour to reduce unnecessary memory usage. Around 4.0.0, this was changed to a seperate file to support multiple modes. Since then, I haven't bothered updating the PlaceholderAPI hook. I can easily add a way to retrieve data based on player's UUIDs  so you'll see this feature in a next release.

> Also I am absolutely positive it wasn't always this way, I've been using it before but at some point it must've broken :(

I don't think that was ever the case, but I'm not sure.

**Comment by Folas1337** [comment]
Alright, I'm also fine with this being an enhancement from now on :)
Thanks for taking it into consideration!

**Comment by en0tuk** [comment]
Also make %witp_highscore% work global
It'll be useful for plugins like ajLeaderboards

**Comment by Efnilite** [comment]
Fixed in https://github.com/Efnilite/Walk-in-the-Park/commit/313c3b42aa8103462fb2e4aee15ff11b765212ee. You'll see it in the next release.
