### ISSUE TITLE
1.8 Support?

### ISSUE THREAD

**Issue by strich3** [Efnilite/Walk-in-the-Park#63]
Could you please make the plugin 1.8 compatible? It would be so great!

**Comment by Efnilite** [comment]
Currently working on adding up to 1.12 support. This is already proving to be quite difficult (since a lot of things I use got added in versions after 1.12), but this is mainly due to the schematics. Do you think people would be okay with having a 1.8-1.12 version without schematics? I can add that pretty easily :)

**Comment by strich3** [comment]
Sure! I just wanna have some fun when no one is online haha, thanks btw :D

**Comment by Efnilite** [comment]
I'll see what I can do 😉

**Comment by Efnilite** [comment]
Currently 1.8 is supported, but I still need to add some defaults to specific things that have changed name over time. Except support soon ;)

**Comment by strich3** [comment]
ok, nice

**Comment by Efnilite** [comment]
After experimenting for a while I have found it to be way too difficult to properly add 1.8 support -- this would require a rewrite of the entire storage system, among other things. Sorry to disappoint, but I don't really believe it to be worth it.
