### ISSUE TITLE
Config changes dont get applied

### ISSUE THREAD

**Issue by LucidAPs** [Efnilite/Walk-in-the-Park#98]
I did the following changes in the config, yet nothing changed, the gui elements are still there for players and can select the disabled options.
https://nekobin.com/hevedetabe

Also focus mode doesn't work.

vilib-1.1.0
IP-4.1.2
mc server 1.19.3

**Comment by Efnilite** [comment]
After your changes, did you use /ip reload to apply them?

**Comment by LucidAPs** [comment]
[rewards-v2.zip](https://github.com/Efnilite/Walk-in-the-Park/files/10980492/rewards-v2.zip)
I tried /ip reload and server restart.

**Comment by Efnilite** [comment]
I deleted all my plugin folders and let a blank config generate. I started the server, and then copied your config, and then performed `/ip reload`. For me, this correctly applied the changes. It could be possible that permissions are causing issues with the enabling/disabling of the options. Can you set `permissions` to false and see if it works?

Also, focus mode may not work on some commands because different plugins deal with commands in different ways, making it hard to make it so it works for every command, but right now it works for most.
